### ISSUE TITLE
The manifest contains invalid XML:

### ISSUE THREAD

**Issue by wuhaoqi-1** [NVIDIA-AI-IOT/ros2_trt_pose#9]
HI,An error occurred when I ran this command `"rosdep install --from-paths src --ignore-src --rosdistro eloquent -y"` 
![image](https://user-images.githubusercontent.com/52825781/116097017-57252480-a6dc-11eb-95af-166f87dc906e.png)

**Comment by the-black-viper** [comment]
I got the same error. What I did was removed the copyright headers. Specifically the lines:
```<!--# -&#45 ... --!>```
I believe the headers corrupted the XML files. I did this for two files in:
1. `ros2_trt_pose/ros2_trt_pose/package.xml`
2. `ros2_trt_pose/pose_msgs/package.xml`

I made a backup before modifying just in case.

**Comment by wuhaoqi-1** [comment]
> I got the same error. What I did was removed the copyright headers. Specifically the lines:
> `<!--# -&#45 ... --!>`
> I believe the headers corrupted the XML files. I did this for two files in:
> 
> 1. `ros2_trt_pose/ros2_trt_pose/package.xml`
> 2. `ros2_trt_pose/pose_msgs/package.xml`
> 
> I made a backup before modifying just in case.

The above problem has been solved, But when I run this command `colcon build`  report an error
![image](https://user-images.githubusercontent.com/52825781/116498602-ac2f8900-a8dc-11eb-8347-48992d8bc16e.png)

**Comment by MiguelOsun** [comment]
Hi!
I have the same problem you had, when i ran the command "rosdep install --from-paths src --ignore-src --rosdistro eloquent -y" i had an error in the xml files too, but when i removed that lines the issue persisted. Do you know why would this happen? I've been a while with this issue and i would appreciate some help. Thank you!
